# Site settings
title: Don't over(look|state) the obvious
tagline: John Damask's personal site
email: jbdamask@gmail.com
description: >
  Personal blog and website
baseurl: ""
url: "https://jbdamask.github.io"
permalink: pretty

# Author information
author: John Damask

# Social media
github_username: jbdamask
twitter_username: jbdamask
linkedin_username: johndamask
medium_username: jbdamask

# Build settings
markdown: kramdown
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_sidebar: false
  -
    scope:
      path: ""
    values:
      layout: "page"
      show_sidebar: false

# RSS feed
rss-description: Not sure why you would subscribe to this but here you go
