#!/usr/bin/env python3
"""
Fetch recent posts from Substack RSS feed and save to _data/substack-posts.yml
"""

import os
import sys
import requests
import yaml
from datetime import datetime

# Configuration
SUBSTACK_FEED = 'https://johndamask.substack.com/feed'
PROXY_URL = 'https://api.rss2json.com/v1/api.json?rss_url='
MAX_POSTS = 10
OUTPUT_FILE = "_data/substack-posts.yml"

def extract_image_from_content(content):
    """Extract first image URL from HTML content"""
    import re
    match = re.search(r'<img[^>]+src="([^"]+)"', content)
    return match.group(1) if match else None

def fetch_substack_posts():
    """Fetch recent posts from Substack RSS feed"""
    try:
        url = PROXY_URL + SUBSTACK_FEED
        response = requests.get(url, timeout=30)

        if response.status_code != 200:
            print(f"Error fetching Substack feed: {response.status_code}")
            return []

        data = response.json()

        if data.get('status') != 'ok':
            print(f"Error in RSS feed response: {data}")
            return []

        posts = []
        for item in data.get('items', [])[:MAX_POSTS]:
            # Parse date
            pub_date = datetime.strptime(item['pubDate'], "%Y-%m-%d %H:%M:%S")

            # Extract image
            thumbnail = item.get('thumbnail') or extract_image_from_content(item.get('content', ''))

            post = {
                'title': item['title'],
                'source': 'substack',
                'url': item['link'],
                'date': pub_date.strftime('%Y-%m-%d'),
                'excerpt': item.get('description', '')[:200] + '...' if len(item.get('description', '')) > 200 else item.get('description', ''),
                'image': thumbnail or ''
            }
            posts.append(post)

        print(f"Fetched {len(posts)} Substack posts")
        return posts

    except Exception as e:
        print(f"Error fetching Substack posts: {e}")
        return []

def main():
    print("Fetching Substack posts...")

    posts = fetch_substack_posts()

    if not posts:
        print("No posts fetched. Keeping existing file if it exists.")
        sys.exit(0)

    # Ensure _data directory exists
    os.makedirs('_data', exist_ok=True)

    # Write to YAML file
    with open(OUTPUT_FILE, 'w') as f:
        f.write("# Substack posts - automatically generated by fetch_substack.py\n")
        f.write("# Do not edit manually - changes will be overwritten\n\n")
        yaml.dump(posts, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"✓ Wrote {len(posts)} posts to {OUTPUT_FILE}")

if __name__ == '__main__':
    main()
