#!/usr/bin/env python3
"""
Fetch all posts from Substack RSS feed and save to _data/substack-posts.yml
"""

import os
import sys
import requests
import yaml
from datetime import datetime
import xml.etree.ElementTree as ET
import re

# Configuration
SUBSTACK_FEED = 'https://substack-rss.jbdamask.workers.dev'
OUTPUT_FILE = "_data/substack-posts.yml"

def extract_image_from_content(content):
    """Extract first image URL from HTML content"""
    match = re.search(r'<img[^>]+src="([^"]+)"', content)
    return match.group(1) if match else None

def strip_html(text):
    """Remove HTML tags from text"""
    return re.sub(r'<[^>]+>', '', text)

def fetch_substack_posts():
    """Fetch all posts directly from Substack RSS feed"""
    try:
        print(f"Fetching from {SUBSTACK_FEED}...")
        response = requests.get(SUBSTACK_FEED, timeout=30)

        if response.status_code != 200:
            print(f"Error fetching Substack feed: {response.status_code}")
            return []

        # Parse XML RSS feed
        root = ET.fromstring(response.content)

        posts = []

        # Find all items in the feed
        for item in root.findall('.//item'):
            title_elem = item.find('title')
            link_elem = item.find('link')
            pub_date_elem = item.find('pubDate')
            description_elem = item.find('description')
            content_elem = item.find('{http://purl.org/rss/1.0/modules/content/}encoded')

            if title_elem is None or link_elem is None or pub_date_elem is None:
                continue

            title = title_elem.text
            link = link_elem.text

            # Parse date (RSS format: "Wed, 22 Nov 2025 10:00:00 GMT")
            pub_date_str = pub_date_elem.text
            pub_date = datetime.strptime(pub_date_str, "%a, %d %b %Y %H:%M:%S %Z")

            # Get description/excerpt
            description = ''
            if description_elem is not None and description_elem.text:
                description = strip_html(description_elem.text)

            # Extract image from content
            image = ''
            if content_elem is not None and content_elem.text:
                image = extract_image_from_content(content_elem.text) or ''

            # Truncate excerpt
            excerpt = description[:200] + '...' if len(description) > 200 else description

            post = {
                'title': title,
                'source': 'substack',
                'url': link,
                'date': pub_date.strftime('%Y-%m-%d'),
                'excerpt': excerpt,
                'image': image
            }
            posts.append(post)

        print(f"Fetched {len(posts)} Substack posts")
        return posts

    except Exception as e:
        print(f"Error fetching Substack posts: {e}")
        import traceback
        traceback.print_exc()
        return []

def main():
    print("Fetching Substack posts...")

    new_posts = fetch_substack_posts()

    if not new_posts:
        print("No posts fetched. Keeping existing file if it exists.")
        sys.exit(1)

    # Ensure _data directory exists
    os.makedirs('_data', exist_ok=True)

    # Load existing posts to preserve history (RSS only returns recent posts)
    existing_posts = []
    if os.path.exists(OUTPUT_FILE):
        try:
            with open(OUTPUT_FILE, 'r') as f:
                existing_posts = yaml.safe_load(f) or []
            print(f"Loaded {len(existing_posts)} existing posts")
        except Exception as e:
            print(f"Warning: Could not load existing posts: {e}")

    # Merge posts: keep existing posts and update/add new ones
    # Create a dictionary of existing posts by URL for fast lookup
    existing_by_url = {post['url']: post for post in existing_posts}

    # Update existing posts or add new ones
    for new_post in new_posts:
        existing_by_url[new_post['url']] = new_post

    # Convert back to list and sort by date (newest first)
    all_posts = list(existing_by_url.values())
    all_posts.sort(key=lambda p: p['date'], reverse=True)

    # Write to YAML file
    with open(OUTPUT_FILE, 'w') as f:
        f.write("# Substack posts - automatically generated by fetch_substack.py\n")
        f.write("# Fetches RSS feed (latest 5) and merges with existing posts\n")
        f.write("# This preserves older posts not in the RSS feed\n\n")
        yaml.dump(all_posts, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"✓ Wrote {len(all_posts)} posts to {OUTPUT_FILE} ({len(new_posts)} from RSS, {len(all_posts) - len(new_posts)} preserved)")

if __name__ == '__main__':
    main()
